# Dependencies
name:                Robert Carroll
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title/

# Setup
title:               Robert Carroll
tagline:             The writing and design of Robert Carroll
url:                 https://www.robertocarroll.com
job_description:     "writer, designer and technologist"
description:         "a tiny design and development studio called <a class='primary' href='https://www.wearethoughtfox.com/'>We Are Thought Fox</a>"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  work:
    output: true
    permalink: /:collection/:slug
  journal:
    output: true
    permalink: /:collection/:slug
  writing:
    output: true
    permalink: /:collection/:slug
  code:
    output: true
    permalink: /:collection/:slug
  reading:
    output: true
    permalink: /:collection/:slug
  scrapbook:
    output: true
    permalink: /:collection/:slug

# About/contact
author:
  name:              Robert Carroll
  url:               https://twitter.com/robertocarroll
  email:             rob@wearethoughtfox.com
  twitter:           robertocarroll

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/robertocarroll/robertocarroll

include:
  - _pages

# Defaults
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/

navigation:
 - title: Work
   url: /work
 - title: Writing
   url: /writing
 - title: Journal
   url: /journal
 - title: About
   url: /about

